### ISSUE TITLE
Feature request: Make cuts through data using the mouse

### ISSUE THREAD

**Issue by henrikjacobsenfys** [MJOLNIRPackage/MJOLNIR#45]
It would be neat to be able to make 1d cuts through the data shown using View3d or plotCutQELine by use of the mouse. E.g. by a command and/or keyboard shortcut, choosing the start and end points of the cut as well as the width. Ideally this would also print out the commands required to make this cut.

**Comment by Jakob-Lass** [comment]
By the addition of the custom viewer3D this feature is now possible as of 334cb034e1e90ffdc98d2bfa42345d0a05972d1f. It is possible to have an interactive view of the scattering plane with variable energy integration. A line through data is chosen and intensity is plotted as a function of energy and distance along the chosen line.
